site_name: FastApi-MQTT
site_url: 
site_description: fastapi-mqtt is client for MQTT protocol
dev_addr: 127.0.0.1:8080

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple
  
  icon:
    repo: fontawesome/brands/github
repo_name: fastapi-mqtt
repo_url: https://github.com/sabuhish/fastapi-mqtt
edit_uri: ''

plugins:
- search
- markdownextradata:
    data: data

markdown_extensions:
  - toc:
      permalink: true
    
nav:
  - FastApi MQTT: index.md
  - 🔨 Installation: install.md
  - 🕹 Getting Started: getting-started.md
  - Example: example.md
  - MQTT: mqtt.md
  - Contribution: contribute.md





